### ISSUE TITLE
Getting import warnings on newest version

### ISSUE THREAD

**Issue by Shushman** [JuliaPOMDP/LocalApproximationValueIteration.jl#14]
On importing after updating to newest version, there's an error that `Random` is not in the package dependencies (even though it is listed in `Project.toml`). Not sure how to fix.

**Comment by MaximeBouton** [comment]
I cannot reproduce the error. I am at version `0.2.1`: 
```
  [a40420fb] LocalApproximationValueIteration v0.2.1 #master (https://github.com/JuliaPOMDP/LocalApproximationValueIteration.jl.git)
```
