### ISSUE TITLE
Decide how to manage interp object between solver and policy

### ISSUE THREAD

**Issue by Shushman** [JuliaPOMDP/LocalApproximationValueIteration.jl#4]
Should the `Solver` have ownership of the `interp` object or just update the `interp` object of the underlying `Policy`? Note that the latter structure is used in `DiscreteValueIteration.jl` so incorporating that will require changing the constructors.

**Comment by zsunberg** [comment]
A solver should be able to solve multiple MDPs and obtain multiple discrete policies, so if I call
```julia
p1 = solve(solver, mdp1)
p2 = solve(solver, mdp2)
```
`p1` and `p2` *must not* contain pointers to the same `interp` object.

Moreover, you should be able to specify all solving options via the solver - you should not need to create a policy object and pass it into `solve()`. In hindsight, I consider allowing the policy to be passed into `solve()` (and the `verbose` keyword argument) bad design choices for DiscreteValueIteration.

Those two considerations might help in making this decision.

**Comment by Shushman** [comment]
Hmm got it - I think the right thing to do is to create a new policy each time `solve` is called with a separate instance of the `interp` object.

**Comment by zsunberg** [comment]
Yeah, I think that is right

**Comment by Shushman** [comment]
Great - that is the current behaviour. When a `Policy` object is constructed (taking the `mdp` and `Solver` as parameters), I call `deepcopy(solver.interp)` so that the `solver.interp` just has the bare structure which is copied each time to the policy object, and the `policy.interp` is what is actually updated in `solve`.
