### ISSUE TITLE
Unable to "add" LocalApproximationValueIteration

### ISSUE THREAD

**Issue by okkhoy** [JuliaPOMDP/LocalApproximationValueIteration.jl#5]
When I try `POMDPs.add("LocalApproximationValueIteration"))` I get the following error: 
```
julia> POMDPs.add("LocalApproximationValueIteration")
ERROR: AssertionError: The JuliaPOMDP package: LocalApproximationValueIteration is not supported
```

How to resolve this?

**Comment by MaximeBouton** [comment]
Hi, 
LocalApproximationValueIteration has not been added to the list of supported solvers yet. 
You can still install it directly by doing: 
`Pkg.clone("https://github.com/JuliaPOMDP/LocalApproximationValueIteration.jl.git")`
and it should work fine. 
We will add it to the list of supported packages as soon as possible.

**Comment by okkhoy** [comment]
Thanks! Was able to set it up.
